### ISSUE TITLE
Crash with Wreng ( 1.10.2)

### ISSUE THREAD

**Issue by Golgatron** [Vanhal/ProgressiveAutomation#284] opened 2016-10-20 13:26 UTC
Hey client crashed with  PA Wrench shift right klick on Planter

**Comment by DnTheMn** [comment] 2016-10-31 06:34
can confirm https://github.com/whatthedrunk/allthemods/issues/228

**Comment by Xalorous** [comment] 2016-11-02 23:09
also confirm http://pastebin.com/04y63DZg

**Comment by Xalorous** [comment] 2016-11-02 23:11
Duplicate of #279

**Comment by Caleb-Ardern** [comment] 2016-11-06 11:23
Temporary fix config line 47 False
this should remove the use of the wrench

**Comment by kythorn** [comment] 2016-11-06 19:08
@Caleb-Ardern unfortunately breaking it without the wrench causes all upgrades to be lost. Still mostly a showstopper for this mod I think.

**Comment by Vanhal** [comment] 2016-11-10 14:21
Should be fixed in 1.10.2-1.6.52

**Closed by Vanhal** 2016-11-10 14:21 UTC
