### ISSUE TITLE
[Bug] NullPointer after placing 

### ISSUE THREAD

**Issue by Techtronik** [Vanhal/ProgressiveAutomation#296] opened 2016-12-03 02:05 UTC
It's not crashing but it just keeps throwing nullpointers when i place a progressive automation machine (any machine) and try to interact with anything else that has an interface. the only things i can access while the machine is placed is the player inventory and PA machine inventory and i need to leave and reload the world to get the items to show up in my inventory after i break the machine

Game Output:
http://pastebin.com/TASvYahX

**Comment by Techtronik** [comment] 2016-12-03 02:26
also, this is in the Skyexchange modpack on the curse launcher

I'm putting the mod list into another paste, i'll edit this when i've finished

**Comment by Vanhal** [comment] 2017-02-09 14:09
Duplicate of #298

**Closed by Vanhal** 2017-02-09 14:09 UTC
