### ISSUE TITLE
Game crashed when putting coal bit into the wooden generator

### ISSUE THREAD

**Issue by damnedsky** [Vanhal/ProgressiveAutomation#309] opened 2017-02-20 14:54 UTC
Hello,
I'm new to Progressive Automation. Made 8 bits from 1 coal and tried putting them in the wooden generator. Game crashed and corrupted the world. I couldn't start up the world anymore.
Hope the crash report helpes!

I also have installed a lot of other mods, all from Curse client except for Optifine, but that one is disabled through the launcher because I only use it on occasion.

Cheers! 

[crash-2017-02-20_16.02.46-server.txt](https://github.com/Vanhal/ProgressiveAutomation/files/787779/crash-2017-02-20_16.02.46-server.txt)

**Comment by Vanhal** [comment] 2017-03-30 14:35
This was actually caused by what ever you had connected to the generator. Fixed now in 1.7.1

**Closed by Vanhal** 2017-03-30 14:35 UTC
