### ISSUE TITLE
AutoCrafter world crashing

### ISSUE THREAD

**Issue by scarless** [Vanhal/ProgressiveAutomation#116] opened 2015-04-06 18:51 UTC
Putting the essence orb[Magical crops] in to the ingredient side of Auto Crafter[Progressive automation] causes the game to crash every time the world is loaded, and instantly.
Singleplayer play

inital crash(server): http://pastebin.com/K0vpKQ6N
reloading crash(server):http://pastebin.com/Srv4b73s
reloading crash(client): http://pastebin.com/5m7KeZ5m

**Comment by Vanhal** [comment] 2015-04-06 18:54
What are you using for fuel?

**Comment by scarless** [comment] 2015-04-06 19:31
it was coal

**Comment by Vanhal** [comment] 2015-04-07 09:50
Hopefully I should have fixed this issue in 1.6.12. If you could give it a try and make sure that it did.
If that didn't solve it the issue is actually with BoP which I'll send them over a bug report.

**Comment by Vanhal** [comment] 2015-04-07 10:25
Actually my fix my not fix this. But i've just pushed a change to BoP that will hopefully solve this.

**Comment by Vanhal** [comment] 2015-04-10 11:43
Issue is (hopefully) fixed on BoPs side

**Closed by Vanhal** 2015-04-10 11:43 UTC
