### ISSUE TITLE
[1.8.9] Miner crashes on server restart

### ISSUE THREAD

**Issue by belathus** [Vanhal/ProgressiveAutomation#261] opened 2016-07-05 21:32 UTC
We got the following crash:
http://pastebin.com/xe0BQ9wy

I had been offline for a while, though I'm sure that the miner is in a loaded chunk and I'm sure it is mine. It had an RFEngine for fuel (so I'm not sure why it references getting fuel values twice), and it had ran for a long time. It was using an unbreakable vanilla stone pickaxe with silk touch and efficiency V.

**Comment by Vanhal** [comment] 2016-07-21 12:56
This one looks like it might be caused by something changing burn time in minetweaker. The miner checks things that it mines to see if any are fuel when it's sorting stuff.

Issue should be fixed from 1.10 onwards, but 1.8.9 is no longer supported.

**Closed by Vanhal** 2016-07-21 12:56 UTC
